@startuml
'https://plantuml.com/class-diagram

class SourceConnector {

}

class SourceConsumer {

}

interface SourceTxLog {

}

interface SourceTxCommitter {

}

interface TransactionManager {

}

interface RoutingEngine {

}

interface MessageBus {

}

class SimpleRuntime {

}
@enduml































